RouletteMeeting/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from accountapp.views import homePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name='home'),
    path('accounts/', include('accountapp.urls')),
    path('meeting/', include('meeting.urls')),
]

urlpatterns += staticfiles_urlpatterns()

accountapp/urls.py
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.forms import UserLoginForm
from accountapp.views import (accountCreateView, accountDeleteView,
                              accountDetailView, passwordUpdateView,
                              usernameUpdateView)

app_name = "accountapp"

urlpatterns = [

    # path('login/', LoginView.as_view(
    #     template_name='accountapp/login.html'), name='login'),
    path(
        'login/',
        views.LoginView.as_view(
            template_name="accountapp/login.html",
            authentication_form=UserLoginForm,
        ),
        name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', accountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', accountDetailView.as_view(), name='detail'),
    path('update_password/<int:pk>',
         passwordUpdateView.as_view(), name='update_password'),
    path('update_username/<int:pk>',
         usernameUpdateView.as_view(), name='update_nickname'),
    path('delete/<int:pk>', accountDeleteView.as_view(), name='delete'),

]

meeting/urls.py
from django.urls import path

from . import views

app_name = "meeting"

urlpatterns = [
    path('', views.index, name='index'),
    path('cmeeting/', views.create_meeting, name='create'),
    path('roulette/',views.roulette, name='roulette'),
]

accountapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class UserModel(AbstractUser):
    nickname = models.CharField(max_length=15)

meeting/models.py
import uuid

from django.db import models


class Meeting(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

accountapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import ModelForm
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from accountapp.models import UserModel


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        label="아이디",
        widget=forms.TextInput(
            attrs={'placeholder': '아이디 입력', }))
    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(
            attrs={
                'placeholder': '비밀번호 입력',
            }
        ))


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(
        label="비밀번호",
        strip=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': '비밀번호 입력(영문,숫자 조합 최소 8자)'
        }),
    )
    password2 = forms.CharField(
        label="비밀번호 확인",
        strip=False,
        widget=forms.PasswordInput,
    )

    class Meta:
        model = UserModel
        fields = ['username', 'password1',
                  'password2', 'nickname']
        labels = {
            'username': '아이디',
            'nickname': '닉네임',
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': '아이디 입력(5자~10자)'
                }
            ),
        }


class passwordUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True


class usernameUpdateForm(ModelForm):
    class Meta:
        model = UserModel
        fields = ['nickname']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     self.fields['password1'].disabled = True
    #     self.fields['password2'].disabled = True

meeting/forms.py
from django import forms

from .models import Meeting


class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = "__all__"

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from accountapp.forms import (RegisterForm, passwordUpdateForm,
                              usernameUpdateForm)
from accountapp.models import UserModel

# Create your views here.


def homePage(request):
    return render(request, 'main.html')


class accountCreateView(CreateView):
    model = UserModel
    form_class = RegisterForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/create.html'


class accountDetailView(DetailView):
    model = UserModel
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


class passwordUpdateView(UpdateView):
    model = UserModel
    form_class = passwordUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountapp/update_password.html'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()


class usernameUpdateView(UpdateView):
    model = UserModel
    form_class = usernameUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountapp/update_nickname.html'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()


class accountDeleteView(DeleteView):
    model = UserModel
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountapp/delete.html'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()

meeting/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render

from meeting.forms import MeetingForm
from meeting.models import Meeting


def index(request):
    try:
        meeting = get_object_or_404(Meeting, id=request.GET.get("room"))
        print(meeting.password, request.GET.get("password"))
        if meeting.password != request.GET.get("password"):
            return JsonResponse({"error": "권한이 없습니다."}, status=400)
        return render(request, 'meeting/index.html', {"meeting": meeting})
    except:
        return JsonResponse({"error":"존재하지 않는 회의입니다."}, status=404)


@login_required
def create_meeting(request):
    if request.method == "POST":
        form = MeetingForm(data=request.POST)
        if form.is_valid():
            meeting = form.save()
            return JsonResponse({
                "id": meeting.id,
                "name": meeting.name,
            }, status=201)
    return JsonResponse({
        "error": "잘못된 접근입니다.",
    }, status=400)

def roulette(request):
    return render(request,'roulette/roulette.html')

accountapp/templates/accountapp/create.html
{% load static %}
{% load bootstrap4 %}

<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>



{% block content %}
    <div style=" max-width: 500px; margin: 4rem auto;">
        <div class="mb-4" style="text-align: center;">
            <h4 style="font-weight: 700;">회원가입</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="POST">
            {% csrf_token %}
            <div style="margin-left: 70px;">
                {% bootstrap_form form layout='inline' form_group_class='mb-3 col-10' label_class='mb-2'%}
            </div>
            <div style="text-align: center;">
                <input type="submit" class="btn btn-danger rounded-pill col-8 mt-3" name="" id="">
            </div>
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% load static %}
{% load bootstrap4 %}

<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" name="" id="">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>

    <div style="text-align: center; margin-top: 50px;">
        <div>
            <h2 style="margin-bottom: 60px;">{{user.nickname}}</h2>
        </div>
        {% if target_user == user %}
        <a href="{% url 'accountapp:update_password' pk=target_user.pk %}" style="color:burlywood">
            <p style="font-size: 30px; font-weight: 700;">비밀번호 변경</p>
        </a>
        <a href="{% url 'accountapp:update_nickname' pk=target_user.pk %}" style="color:burlywood">
            <p style="font-size: 30px; font-weight: 700;">닉네임 변경</p>
        </a>
        <a href="{% url 'accountapp:delete' pk=target_user.pk%}" style="color:burlywood">
            <p style="font-size: 30px; font-weight: 700;">사용자 삭제</p>
        </a>

        
        {% endif %}

        
    </div>
    
    

accountapp/templates/accountapp/login.html
{% load static %}
{% load bootstrap4 %}

<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>

{% block content %}

<div style=" max-width: 500px; margin: 4rem auto;">
    <div class="mb-4" style="text-align: center;">
        <h4 style="font-weight: 700;">로그인</h4>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <div style="margin-left: 70px;">
            {% bootstrap_form form layout='inline' form_group_class='mb-3 col-10' label_class='mb-2'%}
        </div>
        <div style="text-align: center;">
            <input type="submit" class="btn btn-danger rounded-pill col-8 mt-3" name="" id="">
        </div>
    </form>
</div>
{% endblock%}

accountapp/templates/accountapp/update_nickname.html
{% load static %}
{% load bootstrap4 %}

<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4>닉네임 변경</h4>
        </div>
        <form action="{% url 'accountapp:update_nickname' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form form_group_class='mb-4'%}
            <input type="submit" class="btn btn-primary" name="" id="">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/update_password.html
{% load static %}
{% load bootstrap4 %}

<head>
    <link rel="stylesheet" href="{% static 'account.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


</head>


<body>
    <nav class="navbar">
        
        <div class="container-fluid">
            
            
            <a href="{% url 'home' %}">
                <img src="{% static 'target.png' %}"  width="30px">
                <span class="nav_span_left">Roulette Meetings</span>
            </a>

            <span class="nav_span_right">
                <a href="{% url 'home' %}">
                    <span style="color: #e18411; padding-right: 1.5rem; ">Home</span>
                </a>
                                    
                {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span style="color: #0070e2; padding-right: 1.5rem;  ">Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span style="color: #cd2002;  ">SignUp</span>
                </a>
                {% else %}

                <a href="{% url 'accountapp:detail' pk=user.pk%}">
                    <span style="color: #0070e2; padding-right: 1.5rem; ">Mypage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span style="color: #cd2002;  ">Logout</span>
                </a>
                {% endif %}
                    
            </span>
        </div>
         
    </nav>

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4>비밀번호 변경</h4>
        </div>
        <form action="{% url 'accountapp:update_password' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            <div style="margin-left: 70px;">
                {% bootstrap_form form layout='inline' form_group_class='mb-3 col-10' label_class='mb-2'%}
            </div>
            <input type="submit" class="btn btn-primary" name="" id="">
        </form>
    </div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block head %}
<link rel="stylesheet" href="{% static 'main.css' %}">
<link rel="stylesheet" href="{% static 'micromodal.css' %}">
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-md">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'navicon.png' %}" width="30px" style="vertical-align: middle; margin-right: 0.3rem; ">
            <span class="nav_span_left">Roulette Meetings</span>
        </a>

        <!-- 토글 버튼 -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon main-navbar-toggler-icon"></span>
        </button>

        <!-- 메뉴 나오는 곳 -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">
                        <span style="color: #e18411;">Home</span>
                    </a>
                </li>

                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accountapp:login' %}?next={{ request.path }}">
                        <span style="color: #0070e2; ">Login</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accountapp:create' %}">
                        <span style="color: #cd2002; ">SignUp</span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accountapp:detail' pk=user.pk %}">
                        <span style="color: #cd2002;">Mypage</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                        Logout
                    </a>
                </li>
                {% endif %}

                <!-- 드랍다운 메뉴에 표현되는 내용들 -->
                <li class="nav-item dropdown">
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="{% url 'home' %}">
                                <span style="color: #e18411;">Home</span>
                            </a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li>
                            <a class="dropdown-item" href="{% url 'accountapp:login' %}?next={{ request.path }}">
                                <span style="color: #0070e2;">Login</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accountapp:create' %}">
                                <span style="color: #cd2002;">SignUp</span>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a class="dropdown-item" href="{% url 'accountapp:detail' pk=user.pk %}">
                                <span style="color: #0070e2;">Mypage</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                                <span style="color: #cd2002;">Logout</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>



<div class="body_div_left">
    <img src="{% static '최종.png' %}" style="padding-top: 10rem; width: 750px; margin-left: 3rem;">
    <br>
    {% if user.is_authenticated %}
    <button class="button button_newmeeting" id="start-new-meeting-modal-btn">새 회의</button>
    {% endif %}
    <button class="button button_connectmeeting" id="enter-meeting-modal-btn">회의 참가하기</button>
</div>
<div class="body_div_right">
    <img src="{% static '01.png' %}" style="padding-top: 10rem; padding-right: 3rem; width: 700px;">
</div>

{% if user.is_authenticated %}
<!-- 새로운 회의 만들 때 사용하는 모달 -->
<div class="modal micromodal-slide" id="new-meeting-modal" aria-hidden="true">
    <div class="modal__overlay" tabindex="-1" data-micromodal-close>
        <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
            <header class="modal__header">
                <h2 class="modal__title" id="modal-1-title">
                    새 회의 정보를 적어주세요.
                </h2>
                <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
            </header>
            <main class="modal__content" id="modal-1-content">
                회의 이름과 회의에서 사용하실 이름을 적어주세요.
                <br>
                <br>
                <form id="new-meeting-form" method="POST" action="{% url 'meeting:create' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="meeting-name"><strong>회의 이름</strong></label>
                        <input type="text" class="form-control" id="new-meeting-name" placeholder="회의 이름을 적어주세요."
                            required>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="username-for-meeting"><strong>사용할 이름</strong></label>
                        <input type="text" class="form-control" id="username-for-new-meeting"
                            placeholder="회의에서 사용할 이름을 적어주세요." required>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="username-for-meeting"><strong>회의 비밀번호</strong></label>
                        <input type="password" class="form-control" id="password-for-new-meeting"
                            placeholder="회의 비밀번호를 적어주세요." name="password" required>
                    </div>
                    <br>
                    <button type="submit" class="modal__btn modal__btn-primary" id="start-new-meeting-btn">회의
                        시작</button>
                    <button type="button" class="modal__btn" data-micromodal-close
                        aria-label="Close this dialog window">취소</button>
                </form>
            </main>
        </div>
    </div>
</div>
{% endif %}

<!-- 기존 회의 참가할 때 사용하는 모달 -->
<div class="modal micromodal-slide" id="enter-meeting-modal" aria-hidden="true">
    <div class="modal__overlay" tabindex="-1" data-micromodal-close>
        <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
            <header class="modal__header">
                <h2 class="modal__title" id="modal-1-title">
                    참가할 회의 이름과 아이디를 입력해주세요
                </h2>
                <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
            </header>
            <main class="modal__content" id="modal-1-content">
                회의 이름과 회의에서 사용하실 이름을 적어주세요.
                <br>
                <br>
                <form id="enter-meeting-form">
                    <div class="form-group">
                        <label for="meeting-name"><strong>회의 아이디 (URL에서 찾을 수 있습니다.)</strong></label>
                        <input type="text" class="form-control" id="enter-meeting-name" placeholder="회의 이름을 적어주세요."
                            required>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="username-for-meeting"><strong>사용할 이름</strong></label>
                        <input type="text" class="form-control" id="username-for-enter-meeting"
                            placeholder="회의에서 사용할 이름을 적어주세요." required>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="username-for-meeting"><strong>회의 비밀번호</strong></label>
                        <input type="password" class="form-control" id="password-for-enter-meeting"
                            placeholder="회의 비밀번호를 적어주세요." name="password" required>
                    </div>
                    <br>
                    <button type="submit" class="modal__btn modal__btn-primary" id="enter-meeting-btn">회의
                        참가</button>
                    <button type="button" class="modal__btn" data-micromodal-close
                        aria-label="Close this dialog window">취소</button>
                </form>
            </main>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    const meetingRoomBaseUrl = "{% url 'meeting:index' %}";
</script>
<script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
<script src="{% static 'main.js' %}"></script>
{% endblock %}